### ISSUE TITLE
Language switcher

### ISSUE THREAD

**Issue by muskatin** [flarum/flarum.github.io#32]
I'm at the stage of completion of the translation, you can add the language switcher?

**Comment by franzliedke** [comment]
Hi! Thanks for your willingness to contribute.

We currently do not plan to offer translated versions of the documentation on flarum.org. That's because it gets complicated to
- keep them up-to-date,
- control and maintain their quality (because we can not possibly speak all those languages)

I hope you understand that, for now, we will leave this up to community-hosted sites.

@tobscure Please close this if you agree.

**Comment by muskatin** [comment]
Yes, I knew about it. but still translate to the end, it may be required in the future.
Thank you noticed :)
Closed.

**Comment by muskatin** [comment]
"@tobscure Please close this if you agree."
Sorry for the carelessness:)

**Comment by franzliedke** [comment]
Which language are we talking about, by the way?

**Comment by muskatin** [comment]
I speak in Russian, and I am not a professional translator.

**Comment by muskatin** [comment]
My translation check back a few programmers that would not have been stupid things, because I a Web designer.
